name: graystone
version: 0.0.1-dev
description: We build robots !
author: Nicolas Francois  <nicolas.franc@gmail.com>
homepage: https://github.com/nfrancois/greystoke
environnment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  firmata: ">=0.1.3 <0.2.0"
dev_dependencies:
  unittest: ">=0.11.0+4 <0.12.0"
