name: graystone
version: 0.1.0-dev
description: Robots with Dart
author: Nicolas Francois  <nicolas.franc@gmail.com>
homepage: https://github.com/nfrancois/greystoke
environnment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  firmata: ">=0.2.0 <0.3.0"
  gpio_commons:
    path: ../gpio_commons
dev_dependencies:
  unittest: ">=0.11.4 <0.12.0"
